"""
generate_sample_data.py — Generates de-identified sample healthcare data.

Maps to: python/generate_structured.py in sfguide-agentic-ai-for-asset-management
Adapted for: Medicare Part D Patient Safety Stars use case

IMPORTANT: All data generated by this module is SYNTHETIC.
No real PHI/PII is used. Member IDs and all identifiers are randomly generated.
"""

import random
import string
import uuid
from datetime import date, timedelta
from typing import Dict, List

import pandas as pd


def _random_id(prefix: str, length: int = 8) -> str:
    return f"{prefix}{''.join(random.choices(string.digits, k=length))}"


def _random_date(start: date, end: date) -> date:
    delta = (end - start).days
    return start + timedelta(days=random.randint(0, delta))


def _random_ndc() -> str:
    """Generate a plausible-format synthetic NDC (11-digit)."""
    return "".join(random.choices(string.digits, k=11))


def generate_members(n: int = 200, seed: int = 42) -> pd.DataFrame:
    """
    Generate synthetic member records.
    Grain: one row per member.
    PHI level: HIGH (member_id is a synthetic surrogate, not real MBI).
    """
    random.seed(seed)
    states = ["CA", "TX", "FL", "NY", "PA", "OH", "IL", "GA", "NC", "MI"]
    genders = ["M", "F", "U"]
    lics = ["LIS_FULL", "LIS_PARTIAL", "NON_LIS"]
    rows = []
    for _ in range(n):
        rows.append(
            {
                "member_id": _random_id("MBR"),
                "contract_id": _random_id("H", 4),
                "plan_id": _random_id("PBP", 3),
                "state_code": random.choice(states),
                "birth_year": random.randint(1930, 1958),
                "gender_code": random.choice(genders),
                "low_income_subsidy_code": random.choice(lics),
                "enrollment_start_date": str(_random_date(date(2023, 1, 1), date(2024, 1, 1))),
                "enrollment_end_date": None,
                "is_active": True,
            }
        )
    return pd.DataFrame(rows)


def generate_pharmacy_claims(members_df: pd.DataFrame, n_per_member: int = 15, seed: int = 42) -> pd.DataFrame:
    """
    Generate synthetic pharmacy claims.
    Grain: one row per dispensing event (fill).
    PHI level: HIGH (member_id links to member record).

    NOTE: Drug classes and NDCs are synthetic and not validated against
    real formulary or CMS specifications.
    """
    random.seed(seed)
    drug_classes = [
        "STATIN", "ACE_INHIBITOR", "ARB", "SULFONYLUREA",
        "OPIOID", "BENZO", "ANTICHOLINERGIC", "WARFARIN",
        "NSAID", "ANTIDEPRESSANT", "ANTIPSYCHOTIC", "INSULIN",
        "METFORMIN", "DIURETIC", "BETA_BLOCKER",
    ]
    days_supply_options = [30, 60, 90]
    rows = []
    claim_date_start = date(2024, 1, 1)
    claim_date_end = date(2024, 12, 31)

    for _, member in members_df.iterrows():
        for _ in range(n_per_member):
            drug_class = random.choice(drug_classes)
            days_supply = random.choice(days_supply_options)
            fill_date = _random_date(claim_date_start, claim_date_end)
            rows.append(
                {
                    "claim_id": str(uuid.uuid4()),
                    "member_id": member["member_id"],
                    "contract_id": member["contract_id"],
                    "plan_id": member["plan_id"],
                    "ndc": _random_ndc(),
                    "drug_class": drug_class,
                    "days_supply": days_supply,
                    "fill_date": str(fill_date),
                    "quantity_dispensed": random.randint(30, 90),
                    "pharmacy_npi": _random_id("NPI", 10),
                    "prescriber_npi": _random_id("PRV", 10),
                    "paid_amount": round(random.uniform(5.0, 800.0), 2),
                    "measurement_year": 2024,
                }
            )
    return pd.DataFrame(rows)


def generate_drug_reference(seed: int = 42) -> pd.DataFrame:
    """
    Generate synthetic drug reference records.
    Grain: one row per NDC.
    PHI level: NONE.

    NOTE: This is illustrative only. Real drug reference should come from
    official NDC directories, RxNorm, or a validated formulary database.
    """
    random.seed(seed)
    records = [
        {"ndc": _random_ndc(), "drug_name": "SIMVASTATIN", "rxnorm_cui": "36567", "therapeutic_class": "STATIN", "generic_indicator": "Y", "is_high_risk_elderly": False},
        {"ndc": _random_ndc(), "drug_name": "ATORVASTATIN", "rxnorm_cui": "83367", "therapeutic_class": "STATIN", "generic_indicator": "Y", "is_high_risk_elderly": False},
        {"ndc": _random_ndc(), "drug_name": "METFORMIN", "rxnorm_cui": "6809", "therapeutic_class": "BIGUANIDE", "generic_indicator": "Y", "is_high_risk_elderly": False},
        {"ndc": _random_ndc(), "drug_name": "GLIPIZIDE", "rxnorm_cui": "4815", "therapeutic_class": "SULFONYLUREA", "generic_indicator": "Y", "is_high_risk_elderly": True},
        {"ndc": _random_ndc(), "drug_name": "WARFARIN", "rxnorm_cui": "11289", "therapeutic_class": "ANTICOAGULANT", "generic_indicator": "Y", "is_high_risk_elderly": True},
        {"ndc": _random_ndc(), "drug_name": "DIAZEPAM", "rxnorm_cui": "3322", "therapeutic_class": "BENZO", "generic_indicator": "Y", "is_high_risk_elderly": True},
        {"ndc": _random_ndc(), "drug_name": "AMITRIPTYLINE", "rxnorm_cui": "704", "therapeutic_class": "TCA_ANTIDEPRESSANT", "generic_indicator": "Y", "is_high_risk_elderly": True},
        {"ndc": _random_ndc(), "drug_name": "OXYCODONE", "rxnorm_cui": "7804", "therapeutic_class": "OPIOID", "generic_indicator": "Y", "is_high_risk_elderly": True},
        {"ndc": _random_ndc(), "drug_name": "LISINOPRIL", "rxnorm_cui": "29046", "therapeutic_class": "ACE_INHIBITOR", "generic_indicator": "Y", "is_high_risk_elderly": False},
        {"ndc": _random_ndc(), "drug_name": "LOSARTAN", "rxnorm_cui": "52175", "therapeutic_class": "ARB", "generic_indicator": "Y", "is_high_risk_elderly": False},
    ]
    return pd.DataFrame(records)


def generate_mtm_interventions(members_df: pd.DataFrame, seed: int = 42) -> pd.DataFrame:
    """
    Generate synthetic MTM/intervention records.
    Grain: one row per intervention event.
    PHI level: HIGH (member_id).
    """
    random.seed(seed)
    intervention_types = ["CMR", "TMR", "PHARMACIST_CONSULT", "PROVIDER_OUTREACH", "MEMBER_OUTREACH"]
    outcomes = ["COMPLETED", "REFUSED", "NO_RESPONSE", "SCHEDULED", "PENDING"]
    rows = []
    for _, member in members_df.sample(frac=0.4, random_state=seed).iterrows():
        n_interventions = random.randint(1, 3)
        for _ in range(n_interventions):
            itype = random.choice(intervention_types)
            rows.append(
                {
                    "intervention_id": str(uuid.uuid4()),
                    "member_id": member["member_id"],
                    "contract_id": member["contract_id"],
                    "intervention_type": itype,
                    "intervention_date": str(_random_date(date(2024, 1, 1), date(2024, 12, 31))),
                    "outcome": random.choice(outcomes),
                    "pharmacist_npi": _random_id("PHR", 10),
                    "notes_available": random.choice([True, False]),
                    "measurement_year": 2024,
                }
            )
    return pd.DataFrame(rows)


def generate_patient_safety_gaps(members_df: pd.DataFrame, seed: int = 42) -> pd.DataFrame:
    """
    Generate synthetic patient safety gap records.
    Grain: one row per member per measure gap identified.
    PHI level: HIGH (member_id).

    NOTE: Gap logic here is illustrative. Real gap detection must use
    validated measure specifications.
    """
    random.seed(seed)
    measure_codes = ["HRM_V1", "SUPD_V1", "PDC_STATIN", "PDC_RASA", "PDC_DIAB", "DDI_WARFARIN_NSAID"]
    gap_statuses = ["OPEN", "CLOSED", "IN_PROGRESS", "ESCALATED"]
    rows = []
    for _, member in members_df.iterrows():
        n_gaps = random.randint(0, 3)
        for _ in range(n_gaps):
            measure_code = random.choice(measure_codes)
            rows.append(
                {
                    "gap_id": str(uuid.uuid4()),
                    "member_id": member["member_id"],
                    "contract_id": member["contract_id"],
                    "measure_code": measure_code,
                    "gap_detected_date": str(_random_date(date(2024, 1, 1), date(2024, 11, 30))),
                    "gap_status": random.choice(gap_statuses),
                    "risk_score": round(random.uniform(0.1, 1.0), 3),
                    "evidence_summary": f"Synthetic gap for {measure_code}",
                    "measurement_year": 2024,
                }
            )
    return pd.DataFrame(rows)
