-- =============================================================================
-- teardown.sql — Drop all CMS Stars AI Agents objects
--
-- Maps to: scripts/teardown.sql in sfguide-agentic-ai-for-asset-management
-- WARNING: This will permanently delete all data and AI components.
-- =============================================================================

-- Drop Cortex Agents
DROP CORTEX AGENT IF EXISTS CMS_STARS_DB.SCHEMA_RAW.MEASURE_INTERPRETATION_AGENT;
DROP CORTEX AGENT IF EXISTS CMS_STARS_DB.SCHEMA_RAW.PATIENT_SAFETY_GAP_DETECTION_AGENT;
DROP CORTEX AGENT IF EXISTS CMS_STARS_DB.SCHEMA_RAW.OUTREACH_RECOMMENDATION_AGENT;
DROP CORTEX AGENT IF EXISTS CMS_STARS_DB.SCHEMA_RAW.STARS_PERFORMANCE_ANALYTICS_AGENT;
DROP CORTEX AGENT IF EXISTS CMS_STARS_DB.SCHEMA_RAW.AUDIT_EXPLAINABILITY_AGENT;
DROP CORTEX AGENT IF EXISTS CMS_STARS_DB.SCHEMA_RAW.CMS_STARS_ORCHESTRATOR;

-- Drop Cortex Search services
DROP CORTEX SEARCH SERVICE IF EXISTS CMS_STARS_DB.SCHEMA_RAW.MEASURE_DOC_SEARCH;
DROP CORTEX SEARCH SERVICE IF EXISTS CMS_STARS_DB.SCHEMA_RAW.POLICY_DOC_SEARCH;
DROP CORTEX SEARCH SERVICE IF EXISTS CMS_STARS_DB.SCHEMA_RAW.CLINICAL_GUIDANCE_SEARCH;
DROP CORTEX SEARCH SERVICE IF EXISTS CMS_STARS_DB.SCHEMA_RAW.SAFETY_BULLETIN_SEARCH;

-- Drop stages
DROP STAGE IF EXISTS CMS_STARS_DB.SCHEMA_RAW.CMS_DOCUMENT_STAGE;
DROP STAGE IF EXISTS CMS_STARS_DB.SCHEMA_RAW.CMS_SEMANTIC_MODELS_STAGE;

-- Drop schemas and all contained objects
DROP SCHEMA IF EXISTS CMS_STARS_DB.SCHEMA_SEMANTIC CASCADE;
DROP SCHEMA IF EXISTS CMS_STARS_DB.SCHEMA_GOLD CASCADE;
DROP SCHEMA IF EXISTS CMS_STARS_DB.SCHEMA_CURATED CASCADE;
DROP SCHEMA IF EXISTS CMS_STARS_DB.SCHEMA_RAW CASCADE;

-- Drop warehouse
DROP WAREHOUSE IF EXISTS CMS_STARS_WH;

-- Drop database
DROP DATABASE IF EXISTS CMS_STARS_DB CASCADE;

-- Drop roles
DROP ROLE IF EXISTS CMS_STARS_APP_USER;
DROP ROLE IF EXISTS CMS_STARS_AUDITOR;
DROP ROLE IF EXISTS CMS_STARS_CLINICAL;
DROP ROLE IF EXISTS CMS_STARS_ANALYST;
DROP ROLE IF EXISTS CMS_STARS_DATA_ENGINEER;
DROP ROLE IF EXISTS CMS_STARS_ADMIN;
